apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: role02-secret
  namespace: db
  labels:
    cnpg.io/reload: "true"
data:
  username: cm9sZTAy
  password: cGFzc3dvcmQ=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg01-cluster
  namespace: db
spec:
  instances: 1
  storage:
    size: 5Gi
  managed:
    roles:
      - name: role02
        login: true
        ensure: present
        superuser: false
        connectionLimit: 20
        disablePassword: false
        passwordSecret:
          name: role02-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db02
  namespace: db
spec:
  name: db02
  owner: role02
  schemas:
    - name: balli
      owner: role02
  databaseReclaimPolicy: delete
  cluster:
    name: pg01-cluster
  extensions:
    - name: bloom
      ensure: present
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nessiedb
  namespace: db
spec:
  name: nessiedb
  owner: role02
  schemas:
    - name: nessie
      owner: role02
  databaseReclaimPolicy: delete
  cluster:
    name: pg01-cluster
  extensions:
    - name: bloom
      ensure: present