apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: secret-pg-samsoft
  labels:
    cnpg.io/reload: "true"
data:
  username: c2Ftc29mdAo=
  password: cGFzc3dvcmQ=
---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql-18
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
      extensions:
        - name: pgvector
          image:
            reference: ghcr.io/cloudnative-pg/pgvector:0.8.6-202609161208-18-trixie
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg01
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql-18
    major: 18
  postgresql:
    extensions:
      - name: pgvector
    shared_preload_libraries:
      - "pg_cron"
    parameters:
      "cron.database_name": "postgres"
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"
      "auto_explain.log_min_duration": "10s"
  storage:
    size: 5Gi
  managed:
    roles:
      - name: samsoft
        login: true
        ensure: present
        superuser: true
        connectionLimit: 20
        disablePassword: false
        passwordSecret:
          name: secret-pg-samsoft
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bizsure
spec:
  name: bizsure
  owner: samsoft
  schemas:
    - name: warehouse
      owner: samsoft
  databaseReclaimPolicy: delete
  cluster:
    name: pg01
  extensions:
    - name: bloom
      ensure: present
    - name: pg_cron
      ensure: present
    - name: vector
      ensure: present
    - name: pg_trgm
      ensure: present