apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: secret-pg-samsoft
  labels:
    cnpg.io/reload: "true"
data:
  username: c2Ftc29mdAo=
  password: cGFzc3dvcmQ=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster01
spec:
  instances: 1
  storage:
    size: 5Gi
  managed:
    roles:
      - name: samsoft
        login: true
        ensure: present
        superuser: false
        connectionLimit: 20
        disablePassword: false
        passwordSecret:
          name: secret-pg-samsoft
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db01
spec:
  name: db01
  owner: samsoft
  schemas:
    - name: balli
      owner: samsoft
    - name: balle
      owner: samsoft
  databaseReclaimPolicy: delete
  cluster:
    name: cluster01
  extensions:
    - name: bloom
      ensure: present