apiVersion: v1
data:
  username: ZGFnc3Rlcg==
  password: ZGFnc3Rlcg==
kind: Secret
metadata:
  name: dagster-pg-secret
  labels:
    cnpg.io/reload: "true"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: samsoft
      owner: samsoft
  managed:
    roles:
      - name: samsoft
        ensure: present
        comment: Kumar Sambhav Jain
        login: true
        superuser: true
        inRoles:
          - pg_monitor
          - pg_signal_backend
      - name: dagster
        ensure: present
        comment: Kumar Sambhav Jain
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: dagster-pg-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: dagster
spec:
  name: dagster
  owner: dagster
  cluster:
    name: my-postgres