apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mysql-pod-monitor
  namespace: mysql
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-mysql-exporter
  podMetricsEndpoints:
    - targetPort: 9104
      interval: "10s"
      path: /metrics
      tlsConfig:
        insecureSkipVerify: true