apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: my-postgres-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: cluster01-rw.db.svc.cluster.local
    database.port: "5432"
    database.user: "samsoft"
    database.password: "password"
    database.dbname: "db01"
    # Logical decoding settings
    topic.prefix: "db01"
    plugin.name: "pgoutput"
    slot.name: "debezium_slot"
    publication.name: "dbz_publication"
    table.include.list: "public.orders"
    # Conversion and snapshotting
    decimal.handling.mode: "double"
    snapshot.mode: "no_data"
    time.precision.mode: "isostring"
    interval.handling.mode: "string"
    errors.tolerance: "none"
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: my-starrocks-sink-connector-v2
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: com.starrocks.connector.kafka.StarRocksSinkConnector
  tasksMax: 1
  config:
    topics.regex: "db01.public.*"
    starrocks.http.url: "http://sr04-fe-proxy-service.db.svc.cluster.local:8080"
    starrocks.database.name: "dev01"
    starrocks.username: "root"
    starrocks.password: ""
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    tasks.max: "3"
    bufferflush.intervalms: 2000
    sink.properties.strip_outer_array: true
    connect.timeoutms: 3000
    starrocks.topic2table.map: "db01.public.orders:raw_orders"
    transforms: addfield,unwrap
    transforms.addfield.type: com.starrocks.connector.kafka.transforms.AddOpFieldForDebeziumRecord
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    ransforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: rewrite